// Generated by https://quicktype.io

class ComboModel {
  int id;
  int categoria;
  String nome;
  String descricao;
  String valor;
  String createdAt;
  String updatedAt;

  ComboModel({
    this.id,
    this.categoria,
    this.nome,
    this.descricao,
    this.valor,
    this.createdAt,
    this.updatedAt,
  });

  ComboModel.fromJson(Map<String, dynamic> json) 
    : 
    id          = json["id"],
    nome        = json["nome"],
    descricao   = json["descricao"],
    valor       = json["valor"];

}








